version: 2
jobs:
  build:
    working_directory: ~/dummy
    docker:
      - image: circleci/node:7.9
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run lint:css
      - run: npm test
